### ISSUE TITLE
Tag Chromium images

### ISSUE THREAD

**Issue by inancgumus** [grafana/crocochrome#28]
# What

As explained in [the Versioning Chromium Images design document](https://docs.google.com/document/d/1ZbjNIrk-i3DYB1_jklr5Xx4hDc8Px4bP-zIK-TXYsCQ/edit), tag Chromium versions in the format `<semver>-Chromium-<Chromium Version>` like `1.0.0-Chromium-126.0.6478.127` (this is an example).

# Why

* **Security Scans**: Allow images to be automatically scanned for security vulnerabilities.
* **Reproducibility**: Provide unique artifacts for each build to ensure reproducible builds (this will also contribute to the reproducibility of the browser-based SM checks).
* **Debuggability**: Make it easy to see which Chromium version an image is shipped with.
* **Consistency**: Standardize Chromium-image versioning throughout the k6 teams.

Possible downsides:

* Using “-” makes an image’s version a prerelease version, which might not work nicely with some tools (this is to be determined because we have never witnessed such a problem yet).
* Pre-release versions are considered lower versions than non-pre-release versions. For example, 1.0.2 is considered a newer version than 1.0.2-Chromium-1.0.0. So, **it’s vital to use the formatting explained in Proposal 3 consistently for incremental security scans**.

# How

Possible solution: Every release might automatically tag a Chromium image incrementally and attach the Chromium version information.

# Note

Add an `image_name` as explained [here](https://github.com/grafana/patch-all-the-things-configurations/blob/main/container_images/README.md#scanning-container-images-examples) for vulnerability scans.

**Comment by roobre** [comment]
We might want to reevaluate this on the Crocochrome side, as I think this may not apply to crocochrome as well as they apply to `k6-browser-docker`.

We have to consider that, unlike `k6-browser-docker`, crocochrome images are not created on the fly when a test is about to be run, but rather are long-running. The code that runs k6 does not have the flexibility of choosing which chromium (or crocochrome) version is going to be used, it is forced to use what it is already there.

For this reason I'm not entirely sure it is useful for crocochrome to be tagged this way. It will add complexity to our pipelines and cognitive load to humans who want to parse the image name. Of the benefits listed there:

> Security Scans

✅ We already meet this requirement. Crocochrome images are fully semver-compliant, with no caveats. Appending the chromium tag does add caveats.

> Reproducibility

✅ Crocochrome images are fully reproducible at any point in time, thanks to https://github.com/grafana/crocochrome/pull/70

> Debuggability: Make it easy to see which Chromium version an image is shipped with.

This is relatively easy to do by inspecting https://github.com/grafana/crocochrome/blob/836ea816d3950a8ba0db2560e8550afe0787a6a6/Dockerfile#L26
In runtime, it is possible to shell into the pod and run `chromium --version`

> Consistency: Standardize Chromium-image versioning throughout the k6 teams.

This is a good point, but I think the differences on how both our browser images are deployed and used are already significant. I don't see a strong reason to have consistent naming.

In short, I think this issue is sufficiently solved by the https://github.com/grafana/chromium-swiftshader-alpine/ image, which is already tagged with the chromium version and provides the required reproducibility and debuggability. I don't see right now a reason to propagate this to crocochrome too.
